# frozen_string_literal: true

source "https://rubygems.org"

# Stand-alone Sitepress server and compiler.
gem "sitepress", "~> 4.0"

# Server used for the Sitepress preview server.
gem "webrick"

# Templating engines. Under the hood Sitepress uses a slimmed
# down Rails, so rails templating engines should mostly work.
gem "haml-rails"
gem "slim-rails"
gem "markdown-rails"
gem "tailwindcss-rails"
gem "importmap-rails"
gem "stimulus-rails"
gem "turbo-rails"
gem "tailwind_merge"
gem "rouge"
